# Generated by Django 5.2.4 on 2025-07-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_user_password_hash_message_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_body',
            new_name='content',
        ),
    ]
